const KEY='atom-bcc-v01';
let state=load();let view='dashboard';
const titles={dashboard:['Главная','Что требует внимания сегодня'],tasks:['Мои задачи','Контроль исполнения'],projects:['Проекты','Портфель ключевых инициатив'],meetings:['Встречи','Адженда, решения и обязательства'],kpi:['KPI','План, факт и прогноз'],blockers:['Блокеры','Что мешает движению'],decisions:['Решения','Что требует управленческого решения'],teams:['Команды','Ответственные и зоны ответственности'],reports:['Отчеты','Еженедельный контроль'],directories:['Справочники','Управление вариантами и статусами']};
function id(){return Math.random().toString(36).slice(2,10)}
function seed(){return{projects:[{id:id(),name:'Коммерческая аналитика',owner:'Коммерческий блок',status:'В работе',progress:48,deadline:'2026-10-30',priority:'Высокий'},{id:id(),name:'B2B продажи',owner:'Корпоративные продажи',status:'В работе',progress:62,deadline:'2026-11-30',priority:'Высокий'}],tasks:[{id:id(),title:'Собрать владельцев источников данных',project:'Коммерческая аналитика',owner:'Иван',status:'В работе',priority:'Высокий',deadline:'2026-09-14'},{id:id(),title:'Зафиксировать поля лида в ELMA',project:'Коммерческая аналитика',owner:'Иван',status:'Новая',priority:'Высокий',deadline:'2026-09-16'}],meetings:[{id:id(),title:'ELMA: путь лида',date:'2026-09-14',owner:'Коммерческая аналитика',status:'Запланирована',result:''}],kpi:[{id:id(),name:'Источники данных описаны',owner:'Коммерческая аналитика',plan:100,fact:45,unit:'%'}],blockers:[{id:id(),title:'Нет единого владельца схемы ELMA → Альфа-Авто',owner:'IT / Бизнес',impact:'Высокое',deadline:'2026-09-17',status:'Открыт'}],decisions:[{id:id(),title:'Утвердить обязательные поля лида',owner:'Коммерческий директор',deadline:'2026-09-18',status:'Ожидает решения',priority:'Высокий'}],teams:[{id:id(),name:'Коммерческий блок',lead:'Коммерческий директор',area:'Приоритеты, KPI, решения'},{id:id(),name:'ELMA / CRM',lead:'Не назначен',area:'Лид, квалификация, интеграции'},{id:id(),name:'DATA / DWH / BI',lead:'Не назначен',area:'Модель данных, витрины, отчетность'}],directories:{taskStatuses:['Новая','В работе','На проверке','Готово','Отложено'],projectStatuses:['План','В работе','Под риском','Завершен'],priorities:['Низкий','Средний','Высокий','Критический']}}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){return seed()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]))}
function fmt(v){if(!v)return '—';return new Intl.DateTimeFormat('ru-RU').format(new Date(v+'T00:00:00'))}
function badge(v){let s=String(v).toLowerCase(),c='';if(s.includes('готов')||s.includes('заверш')||s.includes('закры'))c='ok';else if(s.includes('риск')||s.includes('ожида')||s.includes('сред'))c='warn';else if(s.includes('высок')||s.includes('крит'))c='danger';return `<span class="badge ${c}">${esc(v)}</span>`}
const content=document.getElementById('content');
document.getElementById('nav').onclick=e=>{const b=e.target.closest('[data-view]');if(!b)return;go(b.dataset.view)};
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('quickAddBtn').onclick=()=>openModal(view==='dashboard'?'tasks':view);
document.getElementById('closeModalBtn').onclick=closeModal;
document.getElementById('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
document.getElementById('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='atom-bcc-export.json';a.click()};
document.getElementById('importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();toast('Импорт завершен')}catch(x){toast('Ошибка файла')}};r.readAsText(f)};
function go(v){view=v;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render();document.getElementById('sidebar').classList.remove('open')}
function render(){let [t,s]=titles[view];pageTitle.textContent=t;pageSubtitle.textContent=s;if(view==='dashboard')return dashboard();if(view==='kpi')return renderKpi();if(view==='reports')return reports();if(view==='directories')return directories();collection(view)}
function metric(l,v,n){return `<div class="metric"><div class="metric-label">${l}</div><div class="metric-value">${v}</div><div class="metric-note">${n}</div></div>`}
function dashboard(){const avg=state.projects.length?Math.round(state.projects.reduce((a,b)=>a+Number(b.progress||0),0)/state.projects.length):0;content.innerHTML=`<div class="grid metrics">${metric('Активные проекты',state.projects.filter(x=>x.status!=='Завершен').length,'портфель')}${metric('Открытые задачи',state.tasks.filter(x=>x.status!=='Готово').length,'к исполнению')}${metric('Блокеры',state.blockers.filter(x=>x.status!=='Закрыт').length,'требуют контроля')}${metric('Решения',state.decisions.filter(x=>x.status.includes('Ожида')).length,'ожидают руководителя')}${metric('Готовность портфеля',avg+'%','средний прогресс')}</div><div class="grid two-col"><div class="card"><div class="section-head"><h3>Сегодня в фокусе</h3><button class="btn secondary" onclick="go('tasks')">Все задачи</button></div>${list(state.tasks.slice(0,6),x=>`${x.title}|${x.project} · ${x.owner} · до ${fmt(x.deadline)}|${badge(x.priority)}`)}</div><div class="card"><div class="section-head"><h3>Требуют решения</h3><button class="btn secondary" onclick="go('decisions')">Все решения</button></div>${list(state.decisions,x=>`${x.title}|${x.owner} · до ${fmt(x.deadline)}|${badge(x.priority)}`)}</div></div><div class="grid two-col"><div class="card"><div class="section-head"><h3>Портфель проектов</h3><button class="btn secondary" onclick="go('projects')">Все проекты</button></div>${state.projects.map(x=>`<div class="list-item"><div class="section-head"><b>${esc(x.name)}</b>${badge(x.status)}</div><div class="list-meta">${esc(x.owner)} · ${x.progress}%</div><div class="progress"><span style="width:${x.progress}%"></span></div></div>`).join('')}</div><div class="card"><div class="section-head"><h3>Критические блокеры</h3><button class="btn secondary" onclick="go('blockers')">Все блокеры</button></div>${list(state.blockers,x=>`${x.title}|${x.owner} · до ${fmt(x.deadline)}|${badge(x.impact)}`)}</div></div>`}
function list(arr,fn){return `<div class="list">${arr.map(x=>{let[a,b,c]=fn(x).split('|');return `<div class="list-item"><div class="section-head"><div class="list-title">${esc(a)}</div>${c||''}</div><div class="list-meta">${esc(b||'')}</div></div>`}).join('')}</div>`}
const cfg={tasks:{heads:['Задача','Проект','Ответственный','Статус','Приоритет','Срок'],row:x=>[x.title,x.project,x.owner,badge(x.status),badge(x.priority),fmt(x.deadline)]},projects:{heads:['Проект','Владелец','Статус','Прогресс','Приоритет','Срок'],row:x=>[x.name,x.owner,badge(x.status),x.progress+'%',badge(x.priority),fmt(x.deadline)]},meetings:{heads:['Встреча','Дата','Команда','Статус','Результат'],row:x=>[x.title,fmt(x.date),x.owner,badge(x.status),x.result||'—']},blockers:{heads:['Блокер','Ответственный','Влияние','Статус','Срок'],row:x=>[x.title,x.owner,badge(x.impact),badge(x.status),fmt(x.deadline)]},decisions:{heads:['Вопрос','Кто решает','Приоритет','Статус','Срок'],row:x=>[x.title,x.owner,badge(x.priority),badge(x.status),fmt(x.deadline)]},teams:{heads:['Команда','Руководитель / владелец','Зона ответственности'],row:x=>[x.name,x.lead,x.area]}};
function collection(type){let c=cfg[type],arr=state[type];content.innerHTML=`<div class="card"><div class="section-head"><h3>${titles[type][0]}</h3><button class="btn primary" onclick="openModal('${type}')">+ Добавить</button></div><div class="toolbar"><input id="search" placeholder="Поиск..."></div><div id="wrap">${table(c,arr,type)}</div></div>`;search.oninput=e=>{let q=e.target.value.toLowerCase();wrap.innerHTML=table(c,arr.filter(o=>Object.values(o).join(' ').toLowerCase().includes(q)),type)}}
function table(c,arr,type){return `<table class="table"><thead><tr>${c.heads.map(h=>`<th>${h}</th>`).join('')}<th></th></tr></thead><tbody>${arr.map(x=>`<tr>${c.row(x).map(v=>`<td>${v}</td>`).join('')}<td><button class="btn secondary" onclick="removeItem('${type}','${x.id}')">Удалить</button></td></tr>`).join('')}</tbody></table>`}
function renderKpi(){content.innerHTML=`<div class="card"><div class="section-head"><h3>KPI</h3><button class="btn primary" onclick="openModal('kpi')">+ Добавить KPI</button></div><div class="grid two-col">${state.kpi.map(x=>{let p=x.plan?Math.min(100,Math.round(x.fact/x.plan*100)):0;return `<div class="list-item"><div class="section-head"><b>${esc(x.name)}</b><b>${p}%</b></div><div class="list-meta">${esc(x.owner)} · план ${x.plan} ${esc(x.unit)} · факт ${x.fact} ${esc(x.unit)}</div><div class="progress"><span style="width:${p}%"></span></div></div>`}).join('')}</div></div>`}
function reports(){content.innerHTML=`<div class="grid two-col"><div class="card"><h3>Недельная управленческая сводка</h3>${list([{a:'Что сделано',b:'Закрыто задач: '+state.tasks.filter(x=>x.status==='Готово').length},{a:'Что в работе',b:'Открыто задач: '+state.tasks.filter(x=>x.status!=='Готово').length},{a:'Что мешает',b:'Открытых блокеров: '+state.blockers.filter(x=>x.status!=='Закрыт').length},{a:'Что требует решения',b:'Ожидают решения: '+state.decisions.filter(x=>x.status.includes('Ожида')).length}],x=>`${x.a}|${x.b}|`)}</div><div class="card"><h3>Логика отчета</h3><div class="list"><div class="list-item">1. Что обещали</div><div class="list-item">2. Что выполнено</div><div class="list-item">3. Причины отклонений</div><div class="list-item">4. План следующей недели</div><div class="list-item">5. Решения руководителя</div></div></div></div>`}
function directories(){let d=state.directories;content.innerHTML=`<div class="grid two-col">${dir('Статусы задач','taskStatuses',d.taskStatuses)}${dir('Статусы проектов','projectStatuses',d.projectStatuses)}${dir('Приоритеты','priorities',d.priorities)}</div>`}
function dir(t,k,a){return `<div class="card"><h3>${t}</h3><div class="list">${a.map((x,i)=>`<div class="list-item section-head"><span>${esc(x)}</span><button class="btn secondary" onclick="removeDir('${k}',${i})">Удалить</button></div>`).join('')}</div><div class="toolbar" style="margin-top:12px"><input id="dir-${k}" placeholder="Новый вариант"><button class="btn primary" onclick="addDir('${k}')">Добавить</button></div></div>`}
const schemas={tasks:[['title','Название','text'],['project','Проект','text'],['owner','Ответственный','text'],['status','Статус','select','taskStatuses'],['priority','Приоритет','select','priorities'],['deadline','Срок','date']],projects:[['name','Название проекта','text'],['owner','Владелец','text'],['status','Статус','select','projectStatuses'],['progress','Прогресс, %','number'],['priority','Приоритет','select','priorities'],['deadline','Срок','date']],meetings:[['title','Тема встречи','text'],['date','Дата','date'],['owner','Команда / владелец','text'],['status','Статус','text'],['result','Результат / решение','textarea']],kpi:[['name','Показатель','text'],['owner','Владелец','text'],['plan','План','number'],['fact','Факт','number'],['unit','Единица','text']],blockers:[['title','Блокер','textarea'],['owner','Ответственный','text'],['impact','Влияние','select','priorities'],['status','Статус','text'],['deadline','Срок','date']],decisions:[['title','Вопрос на решение','textarea'],['owner','Кто принимает решение','text'],['priority','Приоритет','select','priorities'],['status','Статус','text'],['deadline','Срок','date']],teams:[['name','Команда','text'],['lead','Руководитель / владелец','text'],['area','Зона ответственности','textarea']]};
function openModal(type){if(!schemas[type])type='tasks';modalTitle.textContent='Добавить: '+titles[type][0];entityForm.dataset.type=type;entityForm.innerHTML=schemas[type].map(([k,l,kind,dir])=>field(k,l,kind,dir)).join('')+'<div class="form-actions"><button type="button" class="btn secondary" onclick="closeModal()">Отмена</button><button class="btn primary">Сохранить</button></div>';entityForm.onsubmit=submit;modalBackdrop.classList.remove('hidden')}
function field(k,l,kind,dir){if(kind==='select')return `<div class="field"><label>${l}</label><select name="${k}" required>${state.directories[dir].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div>`;if(kind==='textarea')return `<div class="field full"><label>${l}</label><textarea name="${k}" required></textarea></div>`;return `<div class="field"><label>${l}</label><input name="${k}" type="${kind}" required></div>`}
function submit(e){e.preventDefault();let type=e.target.dataset.type,obj={id:id()};new FormData(e.target).forEach((v,k)=>obj[k]=v);['progress','plan','fact'].forEach(k=>{if(k in obj)obj[k]=Number(obj[k])});state[type].push(obj);save();closeModal();go(type);toast('Сохранено')}
function closeModal(){modalBackdrop.classList.add('hidden')}
function removeItem(type,item){state[type]=state[type].filter(x=>x.id!==item);save();render()}
function addDir(k){let el=document.getElementById('dir-'+k),v=el.value.trim();if(!v)return;state.directories[k].push(v);save();render()}
function removeDir(k,i){state.directories[k].splice(i,1);save();render()}
function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),1500)}
window.go=go;window.openModal=openModal;window.closeModal=closeModal;window.removeItem=removeItem;window.addDir=addDir;window.removeDir=removeDir;
render();